name: Bld - Build Fat Jars
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  merge_group:
    branches: [ main, master ]

jobs:
  bld-build-fat-jars:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: eclipse-temurin:21-jdk-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Build fat JAR
        run: |
          apt update
          apt install -y curl
          mkdir -p build-fats
          ./scripts/build.bash mutablemarkdownserver.buildFatJar build-fats/mutablemarkdownserver.jar
