name: Bld - All Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  merge_group:
    branches: [ main, master ]

jobs:
  bld-all-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: eclipse-temurin:21-jdk-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          apt update
          apt install -y curl
          scripts/test.bash --test . --log test_log_file.xml
